=== mrsops/BookStore/Bookstores/bookstore.dtd
<?xml version='1.0' encoding='UTF-8'?>
<!ELEMENT bookstore (book)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT book (title|autores|year|price)*>
<!ATTLIST book
    category CDATA #IMPLIED
    cover CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT title (#PCDATA)>
<!ATTLIST title
    lang CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT autores (author+)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT author (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT year (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT price (#PCDATA)>

=== mrsops/BookStore/Bookstores/bookstore.xml
<<<<<<< HEAD
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE BOOKSTORE SYSTEM "bookstore.dtd">
<bookstore>
    <book category="fiction YA">
        <title lang="en">I am number 4</title>
	<autores>
        	<author>James Frey</author>
                <author>Jobie hughes</author>
	</autores>
        <year>2005</year>
        <price>15.99</price>
    </book>
    <book category="fantasy" cover="hardcover">
        <title lang="en">The name of wind</title>
	<autores>
		<author>Patrick Rothfus</author>
	</autores>
	<year>2007</year>
	<price>13.99</price>
    </book>
    <book category="fiction YA">
        <title lang="en">Half-Blood</title>
	<autores>
        	<author>Jennifer L. Amentrout</author>
	</autores>
        <year>2011</year>
        <price>8.99</price>
    </book>
    <book category="fantasy" cover="softcover">
        <title lang="en">Harry Potter and the Deathly Hallows</title>
	<autores>
        	<author>J. K. Rowling</author>
	</autores>
        <year>2007</year>
        <price>11.36</price>
    </book>
</bookstore>


=======
ï»¿<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE BOOKSTORE SYSTEM "bookstore.dtd">
<bookstore>
    <book category="children">
        <title lang="en">Harry Potter</title>
	<autores>
        	<author>J K. Rowling</author>
	</autores>
        <year>2005</year>
        <price>29.99</price>
    </book>
    <book category="web">
        <title lang="en">XQuery Kick Start</title>
	<autores>
		<author>James McGovern</author>
		<author>Per Bothner</author>
		<author>Kurt Cagle</author>
		<author>James Linn</author>
		<author>Vaidyanathan Nagarajan</author>	
	</autores>
	<year>2003</year>
	<price>49.99</price>
    </book>
    <book category="cooking">
        <title lang="en">Everyday Italian</title>
	<autores>
        	<author>Giada De Laurentiis</author>
	</autores>
        <year>2005</year>
        <price>30.00</price>
    </book>
    <book category="web" cover="paperback">
        <title lang="en">Learning XML</title>
	<autores>
        	<author>Erik T. Ray</author>
	</autores>
        <year>2003</year>
        <price>39.95</price>
    </book>
</bookstore>

>>>>>>> master
